#Main config file
#Developed by Mason King#9052

enchantedBook:
  #Placeholders {name} - name of enchant {roman} - roman numeral for number {number} - integer version of level
  name: "&b&l{name} {roman}"
  lore:
    - "&7{description}"
    - ""
    - "&7&o(( Use /anvil to apply ))"

enchantmentLore: "&c&l{enchant} &7{level}"


enchants:
  freeze:
    cost: 30
    #Description of the enchants
    description: "Chance to give a player slowness when hit with a arrow"
  toxic:
    description: "Chance that the target gets poison"
    cost: 30
  duplication:
    description: "Chance to get double blocks"
    cost: 30
  tank:
    description: "Gain extra hearts when applied to armor"
    cost: 30
  experience:
    description: "Gain experience from stone, coal, and iron"
    cost: 30