name: CustomEnchants
version: '1.0-SNAPSHOT'
main: customenchants.Main
api-version: 1.18
authors: [ Mason ]
description: Custom enchant plugin for warstiner
website: masonking.dev
commands:
  ce:
  anvil: